name: ${COMPOSE_PROJECT_NAME}

services:
  reveal:
    container_name: ${COMPOSE_PROJECT_NAME}_reveal
    build:
      context: .
      dockerfile: Dockerfile
    image: autoc-4-reveal-demo
    ports: 
      - name: web_locahost
        target: 8000
        host_ip: ${HOST_IP:-0.0.0.0}
        published: ${HOST_PORT:-8000}
      - name: web_locahost
        target: 35729
        host_ip: ${HOST_IP:-0.0.0.0}
        published: 35729
    volumes:
      # Montage du dossier de plugin TOC
      - type: bind
        source: ../plugin/AuTOC
        target: /reveal/plugin/AuTOC
      # Montage de l'index.html personnalisé
      - type: bind
        source: ../demo/index.html
        target: /reveal/index.html
    stdin_open: true
    tty: true
